name: mouse_gesture
description: Demonstrates how to use the tray_manager plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bot_toast: ^4.0.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  tray_manager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  uses-material-design: true
  assets:
    - images/
